/**
 * PPTX Export — generates a downloadable PowerPoint from classroom slide scenes.
 * Uses pptxgenjs to produce a .pptx buffer.
 */

import PptxGenJS from "pptxgenjs";
import type { ClassroomData } from "./types";

const SLIDE_W_INCHES = 10;
const SLIDE_H_INCHES = 5.625;
const WB_W = 1000;
const WB_H = 562;

function wbToInch(val: number, axis: "x" | "y" | "w" | "h"): number {
  return (axis === "y" || axis === "h")
    ? (val / WB_H) * SLIDE_H_INCHES
    : (val / WB_W) * SLIDE_W_INCHES;
}

function colorHex(c?: string): string {
  if (!c) return "333333";
  return c.replace("#", "").toUpperCase().padEnd(6, "0");
}

export async function generatePPTX(classroom: ClassroomData): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.title = classroom.topic;
  pptx.subject = "AI Classroom Export";
  pptx.company = "PersonalLearningPro";

  // Cover slide
  const cover = pptx.addSlide();
  cover.background = { color: "1a1a2e" };
  cover.addText(classroom.topic, {
    x: 0.5,
    y: 1.8,
    w: 9,
    h: 1.5,
    fontSize: 36,
    bold: true,
    color: "FFFFFF",
    align: "center",
  });
  cover.addText(`Generated by AI Classroom · ${new Date(classroom.createdAt).toLocaleDateString()}`, {
    x: 0.5,
    y: 3.5,
    w: 9,
    h: 0.5,
    fontSize: 14,
    color: "AAAAAA",
    align: "center",
  });

  for (const scene of classroom.scenes) {
    if (!["slide", "slides"].includes(scene.type)) continue;

    const slide = pptx.addSlide();
    slide.background = { color: "FFFFFF" };

    // Title bar
    slide.addText(scene.title, {
      x: 0.3,
      y: 0.15,
      w: 9.4,
      h: 0.6,
      fontSize: 22,
      bold: true,
      color: "1a1a2e",
    });

    const content = scene.content;
    if (!content) continue;

    // Render PPTist-style elements if present
    const elements: any[] = content.elements || content.slides?.[0]?.elements || [];

    for (const el of elements) {
      if (!el || !el.type) continue;

      const x = wbToInch(el.left ?? el.x ?? 0, "x");
      const y = wbToInch(el.top ?? el.y ?? 0, "y");
      const w = wbToInch(el.width ?? el.w ?? 200, "w");
      const h = wbToInch(el.height ?? el.h ?? 100, "h");

      try {
        if (el.type === "text") {
          const fontSize = el.fontSize || el.defaultFontSize || 18;
          slide.addText(String(el.content || el.text || ""), {
            x,
            y,
            w,
            h,
            fontSize: Math.min(fontSize, 40),
            color: colorHex(el.color || el.fill),
            bold: el.bold || false,
            italic: el.italic || false,
            wrap: true,
          });
        } else if (el.type === "shape") {
          slide.addShape(
            el.shape === "circle" || el.shape === "ellipse"
              ? pptx.ShapeType.ellipse
              : pptx.ShapeType.rect,
            {
              x,
              y,
              w,
              h,
              fill: { color: colorHex(el.fill) },
              line: { color: colorHex(el.border || el.stroke), width: 1 },
            }
          );
        } else if (el.type === "image" && (el.src || el.url)) {
          try {
            slide.addImage({ path: el.src || el.url, x, y, w, h });
          } catch {
            // Skip unavailable images
          }
        }
      } catch {
        // Skip any element that fails to render
      }
    }

    // Fallback: render key points as bullet list if no elements
    if (elements.length === 0 && scene.description) {
      slide.addText(scene.description, {
        x: 0.5,
        y: 1.0,
        w: 9,
        h: 4,
        fontSize: 16,
        color: "333333",
        wrap: true,
        valign: "top",
      });
    }
  }

  // Quiz summary slides
  for (const scene of classroom.scenes) {
    if (scene.type !== "quiz") continue;

    const slide = pptx.addSlide();
    slide.background = { color: "f0f4ff" };
    slide.addText(`Quiz: ${scene.title}`, {
      x: 0.3,
      y: 0.15,
      w: 9.4,
      h: 0.6,
      fontSize: 22,
      bold: true,
      color: "1a1a2e",
    });

    const questions: any[] = scene.content?.questions || [];
    let yPos = 1.0;
    for (let i = 0; i < Math.min(questions.length, 4); i++) {
      const q = questions[i];
      if (!q) continue;
      slide.addText(`${i + 1}. ${q.question || q.text || ""}`, {
        x: 0.5,
        y: yPos,
        w: 9,
        h: 0.5,
        fontSize: 14,
        bold: true,
        color: "222222",
      });
      yPos += 0.55;
    }
  }

  const buffer = (await pptx.write({ outputType: "arraybuffer" })) as ArrayBuffer;
  return Buffer.from(buffer);
}
