export const FONTS = [
  { label: '', value: '' },
  { label: '', value: 'SourceHanSans' },
  { label: '', value: 'SourceHanSerif' },
  { label: 'PL', value: 'WenDingPLKaiTi' },
  { label: 'PL', value: 'WenDingPLSongTi' },
  { label: '', value: 'ZhuqueFangSong' },
  { label: '', value: 'LXGWWenKai' },
  { label: '', value: 'AlibabaPuHuiTi' },
  { label: 'MiSans', value: 'MiSans' },
  { label: '', value: 'DeYiHei' },
  { label: '', value: 'CangerXiaowanzi' },
  { label: '', value: 'YousheTitleBlack' },
  { label: '', value: 'FengguangMingrui' },
  { label: '', value: 'ShetuModernSquare' },
  { label: '', value: 'ZcoolHappy' },
  { label: '', value: 'ZizhiQuXiMai' },
  { label: '', value: 'SucaiJishiKangkang' },
  { label: '', value: 'SucaiJishiCoolSquare' },
  { label: '', value: 'TuniuRounded' },
  { label: '', value: 'RuiziZhenyan' },
  { label: 'Source Serif 4', value: 'SourceSerif4' },
  { label: 'JetBrains Mono', value: 'JetBrainsMono' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'OpenSans' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Source Sans Pro', value: 'SourceSansPro' },
  { label: 'Merriweather', value: 'Merriweather' },
];
